export const ApiPath = {
    API_LOGIN: "login",
    API_HOT_PRODUCTS: "product-hot",
    API_GET_CART: "buyer/get-cart",
    API_EDIT_CART: "buyer/edit-cart",
    API_GET_DETAIL_PRODUCT: "detail-product",
    API_POST_COMMENT: "/buyer/comment",
    API_POST_ORDER: "/buyer/order",
    API_GET_PRODUCT_IN_SHOP: "/product-in-shop/",
    API_ADMIN_GET_USER: "admin/get-user",
    API_ADMIN_GET_SHOP: "admin/get-shop",
    API_ADMIN_EDIT_SHOP: "admin/edit-shop",
    API_ADMIN_CREATE_SHOP: "admin/create-shop",
    API_ADMIN_DELETE_SHOP: "admin/del-shop",
    API_ADMIN_GET_COMMENT: "admin/get-comment",
    API_ADMIN_GET_ORDER: "admin/get-order",
    API_ADMIN_EDIT_ORDER: "admin/edit-order",
}
