export const ApiPath = {
    API_LOGIN: "login",
    API_REGISTER: "register",
    API_HOT_PRODUCTS: "product-hot",
    API_GET_CART: "buyer/get-cart",
    API_EDIT_CART: "buyer/edit-cart",
    API_GET_LIST_ORDER: "buyer/get-list-order",
    API_GET_DETAIL_PRODUCT: "detail-product",
    API_POST_COMMENT: "/buyer/comment",
    API_POST_ORDER: "/buyer/order",
    API_EDIT_ORDER: "/buyer/edit-order",
    API_COMMENT: "buyer/comment",
    API_GET_PRODUCT_IN_SHOP: "/product-in-shop/",
    API_SELLER_GET_LIST_SHOP: "/seller/get-list-shop",
    API_SELLER_CREATE_SHOP: "seller/create-shop",
    API_SELLER_EDIT_SHOP: "seller/edit-shop",
    API_SELLER_DELETE_SHOP: "seller/del-shop",
    API_SELLER_GET_PRODUCT_IN_SHOP: "seller/get-list-product",
    API_SELLER_DELETE_PRODUCT:"seller/del-product",
    API_SELLER_GET_DETAIL_PRODUCT:"seller/get-product",
    API_SELLER_EDIT_PRODUCT:"seller/edit-product",
    API_SELLER_CREATE_PRODUCT: "seller/create-product",
    API_ADMIN_GET_USER: "admin/get-user",
    API_ADMIN_EDIT_USER: "admin/edit-user",
    API_ADMIN_GET_SHOP: "admin/get-shop",
    API_ADMIN_EDIT_SHOP: "admin/edit-shop",
    API_ADMIN_CREATE_SHOP: "admin/create-shop",
    API_ADMIN_DELETE_SHOP: "admin/del-shop",
    API_ADMIN_GET_COMMENT: "admin/get-comment",
    API_ADMIN_GET_ORDER: "admin/get-order",
    API_ADMIN_EDIT_ORDER: "admin/edit-order",
    API_ADMIN_GET_LIST_PRODUCT: "product-in-shop",
    API_ADMIN_CREATE_PRODUCT: "admin/create-product",
    API_ADMIN_EDIT_PRODUCT: "admin/edit-product",
    API_ADMIN_DELETE_PRODUCT: "admin/del-product",
    API_ADMIN_CHANGE_PROFILE:"/change-profile"
}
