export const RouteUrl = {
    HOME_PATH: "/home",
    LOG_IN: "/log_in",
    SIGN_UP: "/sign_up",
    DETAIL: "/detail",
    CHECKOUT: "/checkout",
    SHOP: "/shop",
    CART: "/cart",
    ORDERS: "/orders",
    CONTACT: "/contact",
    ADMIN: "/admin",
    ADMIN_USER: "/admin/user",
    ADMIN_ORDER: "/admin/order",
    ADMIN_PRODUCT: "/admin/product/:id",
    ADMIN_SHOP: "/admin/shop",
    ADMIN_CREATE_SHOP:"/admin/shop/create",
    ADMIN_COMMENT: "/admin/comment",
    SIGN_IN_ADMIN: "/sign_in",
    PROFILE_ADMIN: "/admin/profile",
    SELLER_HOME: '/seller_home',
    SELLER_PRODUCT_LIST: '/seller/product_list',
    SELLER_CREATE_PRODUCT: '/seller/create_product',
    SELLER_ORDER_LIST: '/seller/order_list',
    SELLER_SHOP: "/seller/shop",
    CHANGE_PASSWORD: 'change_password',

}
